Rent-All Certificate/Rent-All Certificate/Models/Certification.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_All_Certificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int CertificateID { get; set; }
        public int CertificateTypeID { get; set; }
        public int InventoryID { get; set; }
        public string ProductKey { get; set; }
        public int BranchID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CertificateType CertificateType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}

Rent-All Certificate/Rent-All Certificate/Models/Nen3140.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_All_Certificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nen3140
    {
        public int CertificateID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public string File { get; set; }
    
        public virtual Certification Certification { get; set; }
    }
}

Rent-All Certificate/Rent-All Certificate/Controllers/CertificationsController.cs
using System;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Helpers;
using Rent_All_Certificate.Attributes;
using Rent_All_Certificate.Models;

namespace Rent_All_Certificate.Controllers
{
    [LoginValidRole(ValidRoleId = new[] { Roles.TechnicalStaff, Roles.TechnicalAdministrator })]
    public class CertificationsController : Controller
    {
        private RentAllUserEntities db = new RentAllUserEntities();

        // GET: Certifications/Create
        public ActionResult NEN3140()
        {
            ViewBag.BranchID = new SelectList(db.Branch, "BranchID", "BranchName");
            return View();
        }

        // POST: Certifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NEN3140(CertificationsUploadModel model)
        {
            if (ModelState.IsValid)
            {
                var fileSuccessCount = 0;
                foreach (var file in model.Certificates)
                {
                    if (file == null)
                    {
                        continue;
                    }
                    if (file.ContentType != "application/pdf")
                    {
                        ModelState.AddModelError("", "The file :\"" + file.FileName + "\" isn't recognized as a pdf file.");
                        continue;
                    }
                    var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(file.FileName);
                    if (fileNameWithoutExtension != null)
                    {
                        var keys = fileNameWithoutExtension.Split('-');

                        if (keys.Count() != 2)
                        {
                            ModelState.AddModelError("", "The file :\"" + file.FileName + "\" has an incorrect file name.");
                            continue;
                        }

                        int inventoryId;
                        var productKey = keys[0];

                        if (db.Product.Any(p => p.ProductKey == productKey) == false)
                        {
                            ModelState.AddModelError("", "The key :\"" + productKey + "\" was not found.");
                            continue;
                        }

                        bool parsed = Int32.TryParse(keys[1], out inventoryId);

                        if (parsed == false)
                        {
                            ModelState.AddModelError("", "The inventory id from file :\"" + file.FileName + "\" is not a number.");
                            continue;
                        }

                        if (db.Inventory.Any(i => i.ProductKey == productKey && i.InventoryID == inventoryId) == false)
                        {
                            db.Inventory.Add(new Inventory
                            {
                                InventoryID = inventoryId,
                                ProductKey = productKey
                            });
                            db.SaveChanges();
                        }

                        var fileName = productKey + "-" + inventoryId + ".pdf";
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads/NEN3140"), fileName);
                        file.SaveAs(path);

                        model.Certification.InventoryID = inventoryId;
                        model.Certification.CertificateTypeID = CertificationTypes.NEN3140;
                        model.Certification.ProductKey = productKey;
                        model.Certification.EmployeeID = (int)Session["EmployeeID"];
                        model.Certification.Date = DateTime.Now;
                        db.Certification.Add(model.Certification);
                        db.SaveChanges();

                        fileSuccessCount++;
                    }
                }
                ViewBag.FileSuccessCount = fileSuccessCount;
            }
            if (ModelState.IsValid)
            {
                ViewBag.UploadMessage = "Your files have successfully been uploaded.";
                RedirectToAction("NEN3140");
            }
            model.Certificates = null;
            ViewBag.BranchID = new SelectList(db.Branch, "BranchID", "BranchName", model.Certification.BranchID);
            return View(model);
        }

        public ActionResult Hoist()
        {
            ViewBag.BranchID = new SelectList(db.Branch, "BranchID", "BranchName");
            return View();
        }

        // POST: Certifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Hoist(CertificationsUploadModel model)
        {
            if (ModelState.IsValid)
            {
                var fileSuccessCount = 0;
                foreach (var file in model.Certificates)
                {
                    if (file == null)
                    {
                        continue;
                    }
                    if (file.ContentType != "application/pdf")
                    {
                        ModelState.AddModelError("", "The file :\"" + file.FileName + "\" isn't recognized as a pdf file.");
                        continue;
                    }
                    var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(file.FileName);
                    if (fileNameWithoutExtension != null)
                    {
                        var keys = fileNameWithoutExtension.Split('-');

                        if (keys.Count() != 2)
                        {
                            ModelState.AddModelError("", "The file :\"" + file.FileName + "\" has an incorrect file name.");
                            continue;
                        }

                        int inventoryId;
                        var productKey = keys[0];

                        if (db.Product.Any(p => p.ProductKey == productKey) == false)
                        {
                            ModelState.AddModelError("", "The key :\"" + productKey + "\" was not found.");
                            continue;
                        }

                        bool parsed = Int32.TryParse(keys[1], out inventoryId);

                        if (parsed == false)
                        {
                            ModelState.AddModelError("", "The inventory id from file :\"" + file.FileName + "\" is not a number.");
                            continue;
                        }

                        if (db.Inventory.Any(i => i.ProductKey == productKey && i.InventoryID == inventoryId) == false)
                        {
                            db.Inventory.Add(new Inventory
                            {
                                InventoryID = inventoryId,
                                ProductKey = productKey
                            });
                            db.SaveChanges();
                        }

                        var fileName = productKey + "-" + inventoryId + ".pdf";
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads/Hoist"), fileName);
                        file.SaveAs(path);

                        model.Certification.InventoryID = inventoryId;
                        model.Certification.ProductKey = productKey;
                        model.Certification.CertificateTypeID = CertificationTypes.Hoist;
                        model.Certification.EmployeeID = (int)Session["EmployeeID"];
                        model.Certification.Date = DateTime.Now;
                        try
                        {
                            db.Certification.Add(model.Certification);
                            db.SaveChanges();
                            fileSuccessCount++;
                        }
                        catch (DbUpdateException dbex)
                        {
                            var ex = (SqlException)dbex.InnerException.InnerException;
                            foreach (SqlError error in ex.Errors)
                            {
                                if (error.Number == 50000)
                                {
                                    ModelState.AddModelError("", error.Message + " Filename: " + fileName);
                                }
                            }
                        }
                    }
                }
                ViewBag.FileSuccessCount = fileSuccessCount;
            }
            if (ModelState.IsValid)
            {
                ViewBag.UploadMessage = "Your files have successfully been uploaded.";
                RedirectToAction("Hoist");
            }
            model.Certificates = null;
            ViewBag.BranchID = new SelectList(db.Branch, "BranchID", "BranchName", model.Certification.BranchID);
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rent-All Certificate/Rent-All Certificate/Views/Certifications/Hoist.cshtml
@model Rent_All_Certificate.Models.CertificationsUploadModel

@{
    ViewBag.Title = "Upload";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Upload Hoist Certification</h1>
    </div>
</div>


@using (Html.BeginForm("Hoist", "Certifications", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    if (ViewBag.UploadMessage != null)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Success!</strong> @string.Format(ViewBag.UploadMessage)
        </div>
    }
    else if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (ViewBag.FileSuccessCount != null && (int)ViewBag.FileSuccessCount > 0)
            {
                <p>@string.Format("The {0} remaining file(s) have been uploaded.", (int)ViewBag.FileSuccessCount)</p>
            }
        </div>
    }

    <div class="col-md-12">
        <p>
            <table>
                <tr>
                    <td>
                        <strong>
                            Notice!&nbsp;
                        </strong>
                    </td>
                    <td>
                        only PDF files can be uploaded with a maximum of 1 GB in total and with the following filename structure:
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        (ProductKey)-(ProductID).pdf
                    </td>
                </tr>
            </table>
        </p>
        <p>
            <strong>Example:</strong>
            INCL0055-0001.pdf
        </p>
        <br />
    </div>

    <div class="col-md-6">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Certification.BranchID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Certification.BranchID", (SelectList)ViewBag.BranchID, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Certification.BranchID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Certification.BranchID, "Upload", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Certificates, new { type = "file" })
                    <input type="file" name="Certificates" id="Certificates" accept="application/pdf" multiple="multiple" />
                    @Html.ValidationMessageFor(model => model.Certification.BranchID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

Rent-All Certificate/Rent-All Certificate/Views/Certifications/NEN3140.cshtml
@model Rent_All_Certificate.Models.CertificationsUploadModel

@{
    ViewBag.Title = "Upload";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Upload NEN3140 Certification</h1>
    </div>
</div>


@using (Html.BeginForm("NEN3140", "Certifications", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    if (ViewBag.UploadMessage != null)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Success!</strong> @string.Format(ViewBag.UploadMessage)
        </div>
    }
    else if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (ViewBag.FileSuccessCount != null && (int)ViewBag.FileSuccessCount > 0)
            {
                <p>@string.Format("The {0} remaining file(s) have been uploaded.", (int)ViewBag.FileSuccessCount)</p>
            }
        </div>
    }
    <div class="col-md-12">
        <p>
            <table>
                <tr>
                    <td>
                        <strong>
                            Notice!&nbsp;
                        </strong>
                    </td>
                    <td>
                        only PDF files can be uploaded with a maximum of 1 GB in total and with the following filename structure:
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        (ProductKey)-(ProductID).pdf
                    </td>
                </tr>
            </table>
            <br/>
        </p>
        <p>
            <strong>Example:</strong>
            INCL0055-0001.pdf
        </p>
        <br />
    </div>

    <div class="col-md-6">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Certification.BranchID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Certification.BranchID", (SelectList)ViewBag.BranchID, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Certification.BranchID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Certification.BranchID, "Upload", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Certificates, new { type = "file" })
                    <input type="file" name="Certificates" id="Certificates" accept="application/pdf" multiple="multiple" />
                    @Html.ValidationMessageFor(model => model.Certification.BranchID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}